name: "hikari"
description: "Fluid, responsive blog theme for Jekyll"

author: "John Doge"

url: "http://m3xm.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty
highlighter: true

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: m3xm.github.io
ga_tracking_id: UA-47727049-1
